### ISSUE TITLE
Add option to filter out `ok` states

### ISSUE THREAD

**Issue by octplane** [octplane/ansible_stdout_compact_logger#13]
- Source #12, thanks @pierrehenrymuller
- `actionable` callback does that by default

**Comment by savchenko** [comment]
Hey @octplane , are you still (or _do you plan to..._) work on this one?

Callbacks shipped with base support `display_ok_hosts` and `display_skipped_hosts`, so maybe it worth checking these two and then optionally suppress the "OKs" and "SKIPPEDs"?

**Comment by octplane** [comment]
This has been fixed in 01f88a7c5715e1324fb311201233259db84120fb
