### ISSUE TITLE
Debug message does not display when in a loop

### ISSUE THREAD

**Issue by marc-ledent** [octplane/ansible_stdout_compact_logger#18]
The "debug" module does not display anything when in a loop.
Example:
<pre>
- hosts: all
  gather_facts: False
  tasks:
    - name: message loop
      debug:
        msg: "Hello {{item}}"
      with_items:
        - alice
        - bob
</pre>
displays:
<pre>
[16:20:18] message loop | some_host | SUCCESS | 45ms
{                                                 
  - msg: All items completed                      
}                                                 
</pre>

**Comment by octplane** [comment]
We should see something like this:

```
ok: [localhost] => (item=alice) => {
    "msg": "Hello alice"
}
ok: [localhost] => (item=bob) => {
    "msg": "Hello bob"
}
ok: [127.0.0.1] => (item=alice) => {
    "msg": "Hello alice"
}
ok: [127.0.0.1] => (item=bob) => {
    "msg": "Hello bob"
}
```

**Comment by marc-ledent** [comment]
Yes, but we don't...

**Comment by selurvedu** [comment]
I need this as well.

**Comment by octplane** [comment]
Could you try the content of branch `octplane/debug-loop-display`?

**Comment by matthgyver** [comment]
Hi,
I've same problem.
I've tried with content of  branch octplane/debug-loop-display without success.

*(tested on ansible 2.9.2)*

**Comment by prostir** [comment]
Hi,
I've the same problem.
ansible 2.9.6
python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

**Comment by octplane** [comment]
Hello people,

I have pushed a fix:
- You can either call `ansible-playbook` with `-vv`
- Or add `dump_loop_items = True` to `ansible.cfg`

The playbook `test-18.yml` is a test-case

<img width="934" alt="image" src="https://user-images.githubusercontent.com/22177/223546627-76f19fbf-ec18-48e8-8234-b64aafc2c433.png">

**Comment by selurvedu** [comment]
Just in time 😃
Thank you!
