### ISSUE TITLE
When mutliple hosts execute a task, put each on own line

### ISSUE THREAD

**Issue by memelet** [octplane/ansible_stdout_compact_logger#19]
rather than

```
[17:16:42] Create ca cert directory | 10.0.197.195 | SUCCESS | 765ms
10.0.198.55 | SUCCESS | 766ms
10.0.196.132 | SUCCESS | 885ms
```

It might be easier to read if it where
```
[17:16:42] Create ca cert directory
10.0.197.195 | SUCCESS | 765ms
10.0.198.55  | SUCCESS | 766ms
10.0.196.132 | SUCCESS | 885ms
```
(at least I find it much easier to read)

Otherwise, maybe, if all succeeded, something like
```
[17:16:42] Create ca cert directory | 10.0.197.195, 10.0.198.55, 10.0.196.132 | SUCCESS | 765ms
```
But of course this would scale well to lost of hosts. And where to put the timings?

**Comment by pierrehenrymuller** [comment]
Hi,
I have the same request, if multiple hosts this is not easy readable.
Thanks

**Comment by hkienlen** [comment]
Hello,

I'm expecting the same 

Regards

**Comment by octplane** [comment]
I have implemented a change that also applies to all executions, even with a single host. To make this better, I would have to rewrite most of the code to make it slightly buffered.

**Comment by octplane** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/22177/222986855-ddc6605b-9fdf-4be2-bee1-55c734eed8e1.png">
