### ISSUE TITLE
Disable SKIPPED message

### ISSUE THREAD

**Issue by rbouikila** [octplane/ansible_stdout_compact_logger#20]
Hello,

it's beautiful plugin !

How to disable SKIPPED message if display_skipped_hosts  is define to "False" on ansible.cfg.

Thanks

**Comment by donateur** [comment]
We support a few different operating systems and really do NOT want to see skipped hosts.  Our managed nodes each only run perhaps 30% of all tasks.  So showing skipped tasks is really unhelpful and this is why we're not yet using anstomlog.

Can you please add support to hide skipped messages when the variable @rbouikila mentions is enabled?

**Comment by octplane** [comment]
Fixed via https://github.com/octplane/ansible_stdout_compact_logger/commit/01f88a7c5715e1324fb311201233259db84120fb
