### ISSUE TITLE
DISPLAY_SKIPPED_HOSTS ignored

### ISSUE THREAD

**Issue by StratsScorpio** [octplane/ansible_stdout_compact_logger#30]
The Callback ignore the environment variable ANSIBLE_DISPLAY_SKIPPED_HOSTS.

If I set in environenment with `export ANSIBLE_DISPLAY_SKIPPED_HOSTS=false` or in ansible.cfg with `display_skipped_hosts = false` all skipped hosts will be also displayed.

**Comment by octplane** [comment]
Fixed via https://github.com/octplane/ansible_stdout_compact_logger/commit/01f88a7c5715e1324fb311201233259db84120fb
