### ISSUE TITLE
Ignored errors are not displayed that they ignored

### ISSUE THREAD

**Issue by StratsScorpio** [octplane/ansible_stdout_compact_logger#31]
Running a script with error and the task-option `ignore_unreachable: true` is set, the error is displayed in red letters and it continues, but in yml callback there is an addition `...ignoring` .

Final overview displays then also only "ok/changed/unreachable/failed" but no "ok/changed/unreachable/failed/skipped/rescued/ignored".

`: ok=37   changed=17   unreachable=0    failed=0`
`: ok=37   changed=17   unreachable=0    failed=0    skipped=11   rescued=0    ignored=1`

**Comment by octplane** [comment]
New situation. I'll have a look at that soon...

**Comment by octplane** [comment]
This should be fixed now!
