### ISSUE TITLE
Color output in Jenkins not working but showing boxes.

### ISSUE THREAD

**Issue by cgoeller** [octplane/ansible_stdout_compact_logger#32]
I am using Ansible 7.0.0 with Jenkins 2.381

When executing Ansible in a docker container the output of the default stdout-callback was uncolored in my Jenkins environment. The container is started without the "--tty" option of Docker.
When executing the same playbook on a console I get colored output.

With this plugin I get colored output on a normal console, but in Jenkins the output contains additional characters, that cannot be displayed. See the little boxes with question marks in the screenshot.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1073092/222655699-6ae6d8b6-b190-4997-8cb3-4b1bdd9c4263.png">

I would expect that in case color output is not supported in the environment (what is the case here obviously), the log output is just monochrome. Same behaviour as the default log output of Ansible.

Am I doing something wrong here or is it a bug or an unsupported use case?

Anyway, I like this plugin very much. Thanks for the great work!

**Comment by octplane** [comment]
Hello, can you try the PR referenced?

**Comment by cgoeller** [comment]
> Hello, can you try the PR referenced?

I just tested the PR. No more boxes in the log. Works great.

**Comment by octplane** [comment]
Good! Merging now. Thanks for your feedback.

**Comment by octplane** [comment]
Actually, I'll merge later as I managed to create conflicts 🙈
