### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jcheroske** [octplane/ansible_stdout_compact_logger#8]
I just switched my ansible environment over to python3 and I'm hitting a bunch of errors in this logger. I'm not much of a python dev, so I'm kinda stuck at the moment. Is this lib compatible with python3? If not, would you consider porting it? I really love this logger! There is nothing else out there that even comes close.

**Comment by jcheroske** [comment]
Ok, I fixed it. You just need to do two things to get it to run under python3.

1) Remove the call to `reload(sys).setdefaultencoding('utf8')`

2) Add a decode call to the following function:
```python
    def _open_section(self, section_name):
        # pylint: disable=I0011,W0201
        self.tark_started = datetime.now()

        prefix = ''
        if self._task_level > 0:
            prefix = '  ➥'

        self.task_start_preamble = "[{}]{} {} ...".format(
            self.tark_started.strftime("%H:%M:%S"), prefix.encode('utf-8'), section_name).encode("utf8").decode("utf-8")
        sys.stdout.write(self.task_start_preamble)
```

**Comment by octplane** [comment]
Hi!

I thought you added a comment on a workaround you had to apply... Please add some details so I can either fix the code or put that in the documentation! Thanks :)
